### ISSUE TITLE
Add confirmation message and failure message to index page

### ISSUE THREAD

**Issue by snollygolly** [snollygolly/open-hearts#16]
When creating a new game, the user should see a confirmation message with a link to the game if creation was successful (going to `/game?id=ID`). 

If when creating a new game there was an error (the result object passed back from the server has an error property set to true), display and error explaining what went wrong (result.message should have error descriptions in it)

**Comment by cynical89** [comment]
added functionaility and merged. ref: https://github.com/snollygolly/open-hearts/pull/27/commits/0ecfdffe0254972a8d3ce3281d4dd61198601d73
